#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: dell3400
    username: pasilva1
    password: "$y$j9T$Ze4Z6cfoP2ZP4.7s2vaFf0$zjGh0Mb2BMCq8KYxXf9u/b1NGcWKZDH8zGLpNBYFuC1"
  locale: pt_BR
  keyboard:
    layout: br
    variant: abnt2
  timezone: America/Sao_Paulo
  storage:
    layout:
      name: direct
  user-data:
    apt:
      preserve_sources_list: false
    packages:
      - build-essential
      - python3
      - python3-pip
      - python3-venv
      - git
      - curl
      - wget
      - vim
      - code  # Caso VSCode esteja no repositório
      - net-tools
      - openssh-server
      - openssh-client
      - python3-dev
      - libffi-dev
      - libssl-dev
    runcmd:
      - sudo -u patrick pip3 install --upgrade pip setuptools wheel
      - sudo -u patrick pip3 install virtualenv ipython black flake8 pylint jupyter notebook
      - systemctl enable ssh
  late-commands:
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get -y upgrade
    - curtin in-target -- chsh -s /bin/bash patrick
