---
- name: Configuração local estilo cloud-init via Ansible
  hosts: localhost
  become: true

  vars:
    usuario_padrao: pasilva1
    shell_padrao: /bin/bash

  tasks:

    - name: Atualizar cache APT
      apt:
        update_cache: yes

    # Timezone, locale e teclado
    - name: Definir timezone
      timezone:
        name: America/Sao_Paulo

    - name: Gerar locale pt_BR.UTF-8
      locale_gen:
        name: pt_BR.UTF-8
        state: present

    - name: Definir locale padrão
      lineinfile:
        dest: /etc/default/locale
        regexp: '^LANG='
        line: 'LANG=pt_BR.UTF-8'
        create: yes

    - name: Configurar teclado ABNT2 via arquivo de configuração
      copy:
        dest: /etc/default/keyboard
        content: |
          XKBMODEL="abnt2"
          XKBLAYOUT="br"
          XKBVARIANT=""
          XKBOPTIONS=""
      notify: Reconfigurar teclado

    - name: Criar usuário "{{ usuario_padrao }}"
      user:
        name: "{{ usuario_padrao }}"
        shell: "{{ shell_padrao }}"
        create_home: yes
        groups: sudo
        append: yes
        state: present

    # Adiciona repositório e instala VSCode
    - name: Adicionar chave GPG do VS Code
      shell: |
        curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
      args:
        creates: /usr/share/keyrings/microsoft.gpg

    - name: Adicionar repositório do VS Code
      copy:
        dest: /etc/apt/sources.list.d/vscode.list
        content: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"

    # Adiciona repositório e instala Brave Browser
    - name: Adicionar chave GPG do Brave Browser
      shell: |
        curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave.com/static-assets/repo/brave-browser-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/brave-browser-archive-keyring.gpg

    - name: Adicionar repositório do Brave Browser
      copy:
        dest: /etc/apt/sources.list.d/brave-browser-release.list
        content: |
          deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main

    - name: Atualizar cache APT novamente após repositórios
      apt:
        update_cache: yes

    - name: Instalar pacotes requisitados
      apt:
        name:
          - build-essential
          - python3
          - python3-pip
          - python3-venv
          - git
          - curl
          - wget
          - vim
          - code
          - net-tools
          - openssh-server
          - openssh-client
          - python3-dev
          - libffi-dev
          - libssl-dev
          - gimp
          - inkscape
          - libreoffice
          - brave-browser
        state: present

    - name: Baixar instalador do Google Chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/chrome.deb

    - name: Instalar Google Chrome
      apt:
        deb: /tmp/chrome.deb
      ignore_errors: true

    - name: Atualizar pip, setuptools e wheel
      pip:
        name:
          - pip
          - setuptools
          - wheel
        state: latest
        executable: pip3
      become_user: "{{ usuario_padrao }}"

    - name: Instalar ferramentas Python para o usuário
      pip:
        name:
          - virtualenv
          - ipython
          - black
          - flake8
          - pylint
          - jupyter
          - notebook
        executable: pip3
      become_user: "{{ usuario_padrao }}"

    - name: Ativar e iniciar serviço SSH
      systemd:
        name: ssh
        enabled: yes
        state: started

    - name: Atualizar sistema
      apt:
        upgrade: dist

    - name: Alterar shell padrão do usuário
      user:
        name: "{{ usuario_padrao }}"
        shell: "{{ shell_padrao }}"

  handlers:
    - name: Reconfigurar teclado
      command: setupcon
